# Generated by Django 4.2.6 on 2023-11-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_traime_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_responders',
            name='R_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
